#
# Demonstration of 'lighthouse' instance mode combined with vertical scaling (=instance type mixing and priorities)
#
# Defines that:
#  * (t2|t3|t4).*,lighthouse:           All 't2/t3/t4' instances are 'Lighthouse' instances (can be on-demand or spot instance),
#  * c5.large,spot;c5.large:    c5.large Spot instances needs to be scheduled in priority compared to non-Spot c5.large instances,
#  * c5.xlarge:                 and finally, c5.xlarge instances need to be sheduled last (=lowest priority).
#
ec2.schedule.verticalscale.instance_type_distribution: (t2|t3|t4).*,lighthouse;c5.large,spot;c5.large;c5.xlarge
