#!/bin/bash
set -e

if [ -z "$CLONESQUAD_DIR" ]; then
	echo "Please define CLONESQUAD_DIR variable!" ; exit 1
fi
source ${CLONESQUAD_DIR}/scripts/_source-me.sh

export $(grep -v '\[' $CLONESQUAD_PARAMETER_DIR/samconfig.toml | sed 's/ = /=/g' | xargs)
if ! [ -z "$1" ]; then
	export STACK_NAME=$1
	export GroupName=$1
fi

if ! [ -d .venv ]; then
	echo "Updating dependencies..."
	scripts/update-python-requirements
fi

echo "Deploying stack $STACK_NAME..."

build_and_deploy()
{
	set -x
	set -e
	get_parameters
	params=$(get_parameters) GroupName=$STACK_NAME
	sam build && 
	sam deploy --no-confirm-changeset --parameter-overrides "$params" \
		--stack-name=CloneSquad-$STACK_NAME \
		--s3-bucket=$s3_bucket --s3-prefix=$s3_prefix --region=$region \
		--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
}
time build_and_deploy

