#!/bin/bash

set -e

S3_BUCKET=$1
S3_PREFIX=$2
VERSION=$3
OUTPUT_FORMAT=$4

if [ "$VERSION" = "latest" ]; then
	VERSION=$(cat $CLONESQUAD_DIR/VERSION.txt)
fi

if [ -z "$VERSION" ] || [ -z "$S3_BUCKET" ] || [ -z "$S3_PREFIX" ] || [ -z "$OUTPUT_FORMAT" ]; then
	cat <<EOU
Usage: $0 <target_S3_bucket_name> <target_S3_bucket_prefix> <output_format> <requested_version>"
  output_format can be 'tar' or 's3.'
  * 'tar': a TAR file containing CloneSquad deployment files is streamed on stdout.
  * 's3' : $0 will attempt to publish the CloneSuad deployment files to specified S3 bucket/prefix.
EOU
	exit 1
fi

if ! [ -d releases/$VERSION ] ; then
	echo "[ERROR] Can't find version '$VERSION'! (see 'list-version' command)" ; exit 1
fi

cd releases/$VERSION

tmpdir=/tmp/version.$$
mkdir -p $tmpdir
cp * $tmpdir/
echo $VERSION >$tmpdir/VERSION.txt

# Patch template file with user supplied S3 bucket info
${CLONESQUAD_DIR}/tools/patch-s3uri --version $VERSION --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX template.yaml >$tmpdir/template.yaml

case $OUTPUT_FORMAT in
	tar)
		(cd $tmpdir ; tar cf - *)
	;;
	s3|S3)
		(cd $tmpdir ; aws s3 sync . s3://$S3_BUCKET/$S3_PREFIX/)
	;;
	*)
		echo "[ERROR] Unkown output format $OUTPUT_FORMAT!" ; exit 1
	;;
esac

#rm -fr $tmpdir
