#!/bin/bash
set -e

if [ -z "$CLONESQUAD_DIR" ]; then
	echo "Please define CLONESQUAD_DIR variable!" ; exit 1
fi
source ${CLONESQUAD_DIR}/scripts/_source-me.sh

if ! [ -z "$1" ]; then 
	export GroupName=$1
fi

cd src/
export AWS_SAM_LOCAL=true
export LAMBDA_TASK_ROOT=.
export CLONESQUAD_LOGLEVELS="kvtable=INFO,notify=INFO,targetgroup=INFO"
../.venv/bin/python3 app.py

