#!/bin/bash

if [ -z "$CLONESQUAD_DIR" ]; then
	echo "Please define CLONESQUAD_DIR variable!" ; exit 1
fi
source ${CLONESQUAD_DIR}/scripts/_source-me.sh

export PYTHONPATH=$PWD/src/
export AWS_SAM_LOCAL=true
export LAMBDA_TASK_ROOT=.
export CLONESQUAD_LOGLEVELS=${CLONESQUAD_LOGLEVELS:-"kvtable=INFO,notify=INFO,targetgroup=INFO"}

function on_exit() {
	echo "Enable again Main Lambda function..."
	echo 'override:app.disable: ""' | tools/cs-kvtable CloneSquad-$GroupName-Configuration import &>/dev/null
	echo "Done."
}
trap on_exit EXIT

echo "Disable Main Lambda function..."
echo "override:app.disable: 1" | tools/cs-kvtable CloneSquad-$GroupName-Configuration import &>/dev/null

time .venv/bin/python3 src/app.py $*

