#!/bin/bash -e

if [ -z "${CLONESQUAD_DIR}" ]; then
	echo "Please define CLONESQUAD_DIR!" ; exit 1
fi
cd $CLONESQUAD_DIR
source scripts/_source-me.sh

if [ "$1" == "build" ] ; then
	export DOCKER_BUILDKIT=1
	docker build -f build/Dockerfile.runtime-debug -t clonesquad/runtime:debug . 
	exit 0
fi

if [ "$1" == "run" ] ; then
	shift
	docker run -it -e GroupName=$GroupName -e AWS_SAM_LOCAL=true clonesquad/runtime:debug $*
	exit 0
fi

echo "Usage: $0 <build|run>"
exit 1
