#!/bin/bash

source ${CLONESQUAD_DIR}/scripts/_source-me.sh

export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')}
export ACCOUNT_ID=${ACCOUNT_ID:-$(aws sts get-caller-identity | jq -r '.["Account"]')}
FUNCTION_TO_CALL=CloneSquad-Main-$STACK_NAME

sam build 
set -x
sam local invoke $FUNCTION_TO_CALL --parameter-overrides "$(get_parameters)"
