#!/bin/bash

if [ -z "${CLONESQUAD_DIR}" ] ; then
	echo "Please define CLONESQUAD_DIR environmen variable!" ; exit 1
fi
source ${CLONESQUAD_DIR}/scripts/_source-me.sh

tmpfile=/tmp/cs-config.$$
aws lambda invoke --function-name CloneSquad-Discovery-${GroupName} --payload '' $tmpfile 1>/dev/stderr
APIGW_URL=$(jq -r '.["InteractAPIGWUrl"]' <$tmpfile)
APIGW_VPCENDPOINT_URL=$(jq -r '.["ApiGwVpcEndpointDNSEntries"]' <$tmpfile)
APIGW_ID=$(jq -r '.["InteractApi"]' <$tmpfile)
rm -f $tmpfile
#if ! [ -z "$APIGW_VPCENDPOINT_URL" ] ; then
# We use the endpoint VPC URL if available
#	awscurl -H "x-apigw-api-id: $APIGW_ID" https://${APIGW_VPCENDPOINT_URL}/Configuration/Dump?Unstable=$1 | jq .
#else
	awscurl "${APIGW_URL}Configuration?format=json&Unstable=$1" | jq .
#fi
echo "Queried from API Gateway URL: $APIGW_URL" >/dev/stderr
